"""A toolchain writer and a reader run at once, and the writer writes only its own copy.

`tests/e2e/nx_workspace.py` lets every reader of this checkout's toolchain run on any
worker beside any writer, because a writer installs only into a copy of its own. Different
toolchain paths and an unchanged root are not proof of that on their own: both hold when
the writer and the reader merely ran one after the other. So these journeys drive a
writer and a reader through the contract's real declarations in a throwaway copy of this
checkout — real pytest-xdist within a tier, real Nx across two — and read off an ordered
event log both sides write that the reader's toolchain use began after the writer's
toolchain write began and ended before it ended.

The interleaving is made by waiting on facts, never on a clock. The writer takes its own
copy's install lock, records that its write has begun, and holds the write open until the
reader records its use has ended; the reader waits for the write to have begun before
it uses the copy's root toolchain. Each wait also ends on the fact that its counterpart
cannot run beside it — its process exited without the event, no other xdist worker is
alive to run it, or the Nx run has no second task slot — so a serialised run fails on a
named finding rather than hanging. Two negative controls are run as journeys of their
own: a writer that skips its private copy and installs into the copy's root toolchain, as
an undeclared writer would, and the run serialised (`-n 1` within the tier, Nx's
`parallel` of 1 across tiers).
"""

from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, NamedTuple, Self, get_args

import pytest
from nx_workspace import (
    OFFLINE_INSTALLS,
    TOOLCHAIN_WRITER_MARKS,
    WORKSPACE_INSTALL_MARKS,
    isolated_python_root,
)
from waits import timeout as e2e_timeout

# A writer, because it syncs that copy's `.venv` and runs Bun in the copies inside it.
pytestmark = [*WORKSPACE_INSTALL_MARKS, *TOOLCHAIN_WRITER_MARKS]

#: Where, inside the throwaway copy, the probe module is written: among the copy's own
#: journeys, so its conftest, its `nx_workspace` contract and its read guards apply.
PROBE_MODULE = Path("tests") / "e2e" / "test_toolchain_probe_e2e.py"
WRITER = "test_a_writer_rewrites_only_its_own_toolchain"
READER = "test_a_reader_uses_the_provisioned_toolchain"

#: The probe: one writer and one reader, declared through the copy's own contract. Every
#: wait polls the event log and ends on a recorded fact; nothing here sleeps to order
#: anything.
PROBE = f'''
"""Generated by tests/e2e/test_toolchain_isolation_e2e.py: a writer and a reader at once."""

import contextlib
import fcntl
import json
import os
import subprocess
import time
from pathlib import Path

import pytest
from nx_workspace import copy_checkout, rewrites_workspace_toolchain, shares_workspace_install

from orchestrator.root import REPO_ROOT

EVENTS = Path(os.environ["TOOLCHAIN_PROBE_DIR"]) / "events.jsonl"
WORKERS = Path(os.environ["TOOLCHAIN_PROBE_DIR"]) / "workers"
WORKER = os.environ.get("PYTEST_XDIST_WORKER", "")

# Every xdist worker imports this module while it collects, before any test runs, so a
# waiting side can ask which other workers exist and whether they are alive.
if WORKER:
    WORKERS.mkdir(exist_ok=True)
    (WORKERS / WORKER).write_text(str(os.getpid()), encoding="utf-8")


def record(side, event, **facts):
    with EVENTS.open("a+", encoding="utf-8") as log:
        fcntl.flock(log, fcntl.LOCK_EX)
        log.seek(0)
        sequence = sum(1 for _ in log)
        log.write(json.dumps({{"seq": sequence, "side": side, "event": event,
                               "pid": os.getpid(), "worker": WORKER, **facts}}) + "\\n")


def events():
    if not EVENTS.exists():
        return []
    return [json.loads(line) for line in EVENTS.read_text(encoding="utf-8").splitlines()]


def alive(pid):
    try:
        state = Path(f"/proc/{{pid}}/stat").read_text(encoding="utf-8").rsplit(")", 1)[1].split()[0]
    except FileNotFoundError:
        return False
    return state not in ("Z", "X")


def no_slot_for(counterpart):
    """Why nothing can run ``counterpart`` beside this test, or None while something can."""
    if WORKER:
        others = [path for path in WORKERS.iterdir() if path.name != WORKER]
        if not any(alive(int(path.read_text(encoding="utf-8"))) for path in others):
            return f"no other xdist worker is alive to run the {{counterpart}}"
        return None
    if int(os.environ.get("NX_PARALLEL", "0")) < 2:
        return f"the Nx run has no second task slot to run the {{counterpart}} in"
    return None


def await_event(side, counterpart, event):
    while True:
        seen = events()
        if any(e["side"] == counterpart and e["event"] == event for e in seen):
            return
        started = [e for e in seen if e["side"] == counterpart and e["event"] == "start"]
        if started and not alive(started[-1]["pid"]):
            reason = f"the {{counterpart}}'s process exited without recording {{event}}"
        elif any(e["side"] == counterpart and e["event"] == "abandoned" for e in seen):
            reason = f"the {{counterpart}} abandoned the run before recording {{event}}"
        elif not started:
            reason = no_slot_for(counterpart)
        else:
            reason = None
        if reason is not None:
            record(side, "abandoned", awaiting=event, reason=reason)
            raise AssertionError(f"serialised: {{reason}}")
        time.sleep(0.05)


@contextlib.contextmanager
def abandoning(side):
    """Record that ``side`` gave up when it fails, so its counterpart's wait ends on that."""
    try:
        yield
    except BaseException as failure:
        if not any(e["side"] == side and e["event"] == "abandoned" for e in events()):
            record(side, "abandoned", reason=f"{{type(failure).__name__}}: {{failure}}")
        raise


def toolchain(root):
    return str((root / "node_modules").resolve())


@shares_workspace_install
@rewrites_workspace_toolchain
@pytest.mark.reads_docs
def {WRITER}(tmp_path):
    record("writer", "start")
    if os.environ.get("TOOLCHAIN_PROBE_SKIP_COPY"):
        # Negative control: a writer that installs where it runs, as an undeclared one does.
        target = REPO_ROOT
    else:
        target = tmp_path / "private"
        copy_checkout(target)
    shim = target / "node_modules" / ".bin" / "nx"
    (target / ".logs").mkdir(exist_ok=True)
    with abandoning("writer"), (target / ".logs" / "workspace-install.lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        record("writer", "write-begin", toolchain=toolchain(target),
               shim_before=shim.lstat().st_ino)
        await_event("writer", "reader", "use-begin")
        installed = subprocess.run(["bun", "install", "--frozen-lockfile"], cwd=target,
                                   text=True, capture_output=True, check=False)
        assert installed.returncode == 0, installed.stdout + installed.stderr
        await_event("writer", "reader", "use-end")
        record("writer", "write-end", toolchain=toolchain(target),
               shim_after=shim.lstat().st_ino)


@shares_workspace_install
def {READER}():
    record("reader", "start")
    await_event("reader", "writer", "write-begin")
    with abandoning("reader"):
        record("reader", "use-begin", toolchain=toolchain(REPO_ROOT))
        nx = subprocess.run([str(REPO_ROOT / "node_modules" / ".bin" / "nx"), "--version"],
                            cwd=REPO_ROOT, text=True, capture_output=True, check=False)
        assert nx.returncode == 0, nx.stdout + nx.stderr
        prefix = subprocess.run(["uv", "run", "python", "-c", "import sys; print(sys.prefix)"],
                                cwd=REPO_ROOT, text=True, capture_output=True, check=False)
        assert prefix.returncode == 0, prefix.stdout + prefix.stderr
        record("reader", "use-end", toolchain=toolchain(REPO_ROOT),
               prefix=prefix.stdout.strip())
'''

#: The two Nx projects that run one probe test each, so one real Nx invocation runs the
#: writer's target beside the reader's.
PROBE_PROJECTS = {"toolchain-probe-writer": WRITER, "toolchain-probe-reader": READER}

#: The findings each negative control must fail on, by the assertion that names it.
OVERLAP_FINDING = "the reader's toolchain use did not run inside the writer's write"
ISOLATION_FINDING = "the writer wrote the reader's toolchain"


#: Which side of the probe wrote an event, and what it recorded: the probe's own vocabulary.
Side = Literal["writer", "reader"]
Event = Literal["start", "write-begin", "write-end", "use-begin", "use-end", "abandoned"]


class Entry(NamedTuple):
    """One directory entry as an install leaves it: which inode, last changed when."""

    inode: int
    modified_ns: int


@dataclass(frozen=True)
class ProbeEvent:
    """One line of the event log the probe's writer and reader append to, in order."""

    seq: int
    side: Side
    event: Event
    pid: int
    toolchain: str | None = None
    prefix: str | None = None
    shim_before: int | None = None
    shim_after: int | None = None
    reason: str | None = None

    @classmethod
    def parse(cls, line: str) -> Self:
        recorded = json.loads(line)
        side, event = recorded["side"], recorded["event"]
        assert side in get_args(Side) and event in get_args(Event), recorded
        return cls(
            seq=int(recorded["seq"]),
            side=side,
            event=event,
            pid=int(recorded["pid"]),
            toolchain=recorded.get("toolchain"),
            prefix=recorded.get("prefix"),
            shim_before=recorded.get("shim_before"),
            shim_after=recorded.get("shim_after"),
            reason=recorded.get("reason"),
        )


@dataclass(frozen=True)
class Copy:
    """A throwaway copy of this checkout, carrying the probe."""

    root: Path

    def install_entries(self) -> dict[str, Entry]:
        """What an install into the copy's root toolchain would rewrite, entry by entry.

        Every package directory of `node_modules`, every shim of its `.bin` and every
        entry of `.venv/bin`, read without following a link: a re-link, a reinstall or a
        sync replaces an entry here, which changes its inode or its modification time.
        """
        entries: dict[str, Entry] = {}
        for directory in (
            self.root / "node_modules",
            self.root / "node_modules" / ".bin",
            self.root / ".venv" / "bin",
        ):
            for entry in sorted(directory.iterdir()):
                held = entry.lstat()
                entries[str(entry.relative_to(self.root))] = Entry(held.st_ino, held.st_mtime_ns)
        return entries


@dataclass(frozen=True)
class Run:
    """What one run of the probe recorded, and the copy's root toolchain around it."""

    completed: subprocess.CompletedProcess[str]
    events: list[ProbeEvent]
    before: dict[str, Entry]
    after: dict[str, Entry]

    def event(self, side: Side, name: Event) -> ProbeEvent | None:
        return next(
            (event for event in self.events if event.side == side and event.event == name),
            None,
        )


@pytest.fixture(scope="module")
def copy(tmp_path_factory: pytest.TempPathFactory) -> Copy:
    """A copy of this checkout with its own toolchain, the probe, and its Nx projects.

    One per worker: the journeys on a worker run one after another, each run records into
    a directory of its own, and each reads the copy's root toolchain on either side of
    its own run.
    """
    root = isolated_python_root(tmp_path_factory.mktemp("toolchain-isolation") / "checkout")
    (root / PROBE_MODULE).write_text(PROBE, encoding="utf-8")
    for project, test in PROBE_PROJECTS.items():
        directory = root / "tests" / "toolchain_probe" / project
        directory.mkdir(parents=True)
        command = f"uv run pytest {PROBE_MODULE}::{test} --no-cov -n 0 -p no:cacheprovider"
        (directory / "project.json").write_text(
            json.dumps(
                {
                    "name": project,
                    "targets": {
                        "probe": {
                            "command": command,
                            "options": {"cwd": "."},
                            "cache": False,
                        }
                    },
                }
            ),
            encoding="utf-8",
        )
    return Copy(root)


def _environment(probe: Path, *, skip_copy: bool) -> dict[str, str]:
    probe.mkdir()
    environment = {
        name: value
        for name, value in os.environ.items()
        if name not in {"UV_PROJECT_ENVIRONMENT", "VIRTUAL_ENV", "PYTEST_XDIST_WORKER"}
    }
    return {
        **environment,
        **OFFLINE_INSTALLS,
        "TOOLCHAIN_PROBE_DIR": str(probe),
        "NX_DAEMON": "false",
        **({"TOOLCHAIN_PROBE_SKIP_COPY": "1"} if skip_copy else {}),
    }


def _read(
    copy: Copy,
    probe: Path,
    completed: subprocess.CompletedProcess[str],
    before: dict[str, Entry],
) -> Run:
    log = probe / "events.jsonl"
    recorded = log.read_text(encoding="utf-8").splitlines() if log.exists() else []
    events = [ProbeEvent.parse(line) for line in recorded]
    return Run(completed, events, before, copy.install_entries())


def _within_a_tier(copy: Copy, probe: Path, workers: int, *, skip_copy: bool = False) -> Run:
    """Both probe tests in one real pytest run of the copy, on ``workers`` xdist workers."""
    before = copy.install_entries()
    completed = subprocess.run(
        [
            "uv",
            "run",
            "pytest",
            str(PROBE_MODULE),
            "--no-cov",
            "-p",
            "no:cacheprovider",
            "-n",
            str(workers),
            "--dist",
            "loadgroup",
        ],
        cwd=copy.root,
        env=_environment(probe, skip_copy=skip_copy),
        text=True,
        capture_output=True,
        timeout=e2e_timeout(600),
        check=False,
    )
    return _read(copy, probe, completed, before)


def _across_tiers(copy: Copy, probe: Path, parallel: int, *, skip_copy: bool = False) -> Run:
    """Each probe test as its own target, in one real Nx run of ``parallel`` slots."""
    before = copy.install_entries()
    completed = subprocess.run(
        [
            str(copy.root / "node_modules" / ".bin" / "nx"),
            "run-many",
            "-t",
            "probe",
            f"--projects={','.join(PROBE_PROJECTS)}",
            "--skip-nx-cache",
            "--outputStyle=stream",
        ],
        cwd=copy.root,
        env={
            **_environment(probe, skip_copy=skip_copy),
            # Nx's own setting for how many tasks it runs at once, which every task it
            # starts inherits, so a waiting side can read what slots the run has.
            "NX_PARALLEL": str(parallel),
            "NX_NO_CLOUD": "true",
        },
        text=True,
        capture_output=True,
        timeout=e2e_timeout(600),
        check=False,
    )
    return _read(copy, probe, completed, before)


def _assert_overlapping_and_isolated(copy: Copy, run: Run) -> None:
    """The reader used the root toolchain inside the writer's write, and the write was the
    writer's own.

    Overlap first, so a serialised run fails there; isolation second, so a run whose
    writer shared the root install fails there, having overlapped.
    """
    output = run.completed.stdout + run.completed.stderr
    began = run.event("writer", "write-begin")
    ended = run.event("writer", "write-end")
    used = run.event("reader", "use-begin")
    done = run.event("reader", "use-end")
    assert began and ended and used and done, f"{OVERLAP_FINDING}: {run.events}\n{output}"
    assert began.seq < used.seq < done.seq < ended.seq, f"{OVERLAP_FINDING}: {run.events}"

    writer = ended.toolchain
    reader = done.toolchain
    assert writer != reader and run.before == run.after, (
        f"{ISOLATION_FINDING}: the writer installed into {writer}, the reader read {reader}, "
        f"and the copy's root toolchain {'changed' if run.before != run.after else 'held'}"
    )
    assert reader == str((copy.root / "node_modules").resolve()), reader
    assert done.prefix == str(copy.root / ".venv"), done
    assert began.shim_before != ended.shim_after, "the writer's install wrote nothing"
    assert run.completed.returncode == 0, output


def test_within_a_tier_a_reader_runs_inside_a_writers_install_of_its_own(
    copy: Copy, tmp_path: Path
) -> None:
    """Two xdist workers, one writer and one reader: they overlap, and nothing is shared."""
    _assert_overlapping_and_isolated(copy, _within_a_tier(copy, tmp_path / "probe", workers=2))


def test_across_tiers_a_readers_target_runs_inside_a_writers_install_of_its_own(
    copy: Copy, tmp_path: Path
) -> None:
    """One Nx run of two slots, a writer's target beside a reader's: the same proof."""
    _assert_overlapping_and_isolated(copy, _across_tiers(copy, tmp_path / "probe", parallel=2))


@pytest.mark.parametrize("tier", ["within", "across"])
def test_the_journey_fails_on_its_isolation_finding_when_the_writer_skips_its_copy(
    copy: Copy, tmp_path: Path, tier: str
) -> None:
    """Negative control: a writer installing into the root toolchain fails the proof."""
    run = (
        _within_a_tier(copy, tmp_path / "probe", workers=2, skip_copy=True)
        if tier == "within"
        else _across_tiers(copy, tmp_path / "probe", parallel=2, skip_copy=True)
    )
    with pytest.raises(AssertionError, match=ISOLATION_FINDING):
        _assert_overlapping_and_isolated(copy, run)


@pytest.mark.parametrize("tier", ["within", "across"])
def test_the_journey_fails_on_its_overlap_finding_when_the_run_is_serialised(
    copy: Copy, tmp_path: Path, tier: str
) -> None:
    """Negative control: one xdist worker, or one Nx slot, and the proof fails, unhung."""
    run = (
        _within_a_tier(copy, tmp_path / "probe", workers=1)
        if tier == "within"
        else _across_tiers(copy, tmp_path / "probe", parallel=1)
    )
    with pytest.raises(AssertionError, match=OVERLAP_FINDING):
        _assert_overlapping_and_isolated(copy, run)
    abandoned = [event for event in run.events if event.event == "abandoned"]
    assert abandoned and str(abandoned[0].reason).startswith(("no other", "the Nx run")), (
        f"the serialised run should end on the fact that nothing could run the counterpart: "
        f"{run.events}"
    )
